/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento-sucesso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiPublicVerifyPaymentRouteImport } from './routes/api/public/verify-payment'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento-sucesso',
  path: '/pagamento-sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyPaymentRoute = ApiPublicVerifyPaymentRouteImport.update({
  id: '/api/public/verify-payment',
  path: '/api/public/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagamento-sucesso': typeof PagamentoSucessoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagamento-sucesso': typeof PagamentoSucessoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagamento-sucesso': typeof PagamentoSucessoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pagamento-sucesso'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/api/public/verify-payment'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pagamento-sucesso'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/api/public/verify-payment'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/pagamento-sucesso'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/api/public/verify-payment'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  TermosRoute: typeof TermosRoute
  ApiPublicVerifyPaymentRoute: typeof ApiPublicVerifyPaymentRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-sucesso': {
      id: '/pagamento-sucesso'
      path: '/pagamento-sucesso'
      fullPath: '/pagamento-sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-payment': {
      id: '/api/public/verify-payment'
      path: '/api/public/verify-payment'
      fullPath: '/api/public/verify-payment'
      preLoaderRoute: typeof ApiPublicVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  TermosRoute: TermosRoute,
  ApiPublicVerifyPaymentRoute: ApiPublicVerifyPaymentRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
